name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pytest tests
      env:
        ADZUNA_APP_ID: ${{ secrets.ADZUNA_APP_ID }}
        ADZUNA_API_KEY: ${{ secrets.ADZUNA_API_KEY }}
        USA_JOBS_API_KEY: ${{ secrets.USA_JOBS_API_KEY }}
        USA_JOBS_EMAIL: ${{ secrets.USA_JOBS_EMAIL }}